// Data for learning React concepts: rendering lists, conditional rendering, state, event handling, forms, map, filter, etc.
// Each item has properties to demonstrate various React features
export const allData = [
    {
        id: "g01",
        name: "Laptop Pro",
        price: 75000,
        originalPrice: 85000,
        image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        description: "High-performance laptop with advanced features",
        category: "Electronics",
        subcategory: "Computers",
        rating: 4.7,
        reviews: 245,
        inStock: true,
        discount: 12,
        featured: true,
        tags: ["new", "popular", "professional"],
        specifications: {
            ram: "16GB",
            storage: "512GB SSD",
            processor: "Intel i7",
            os: "Windows 11",
        },
    },
    {
        id: "g02",
        name: "Smartphone X",
        price: 35000,
        originalPrice: null,
        image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        description: "Latest smartphone with cutting-edge technology",
        category: "Electronics",
        subcategory: "Phones",
        rating: 4.3,
        reviews: 189,
        inStock: true,
        discount: 0,
        featured: false,
        tags: ["new", "camera"],
        specifications: {
            ram: "8GB",
            storage: "128GB",
            camera: "48MP",
            battery: "4000mAh",
        },
    },
    {
        id: "g03",
        name: "Wireless Headphones",
        price: 4500,
        originalPrice: 6000,
        image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        description: "Premium noise-cancelling wireless headphones",
        category: "Electronics",
        subcategory: "Audio",
        rating: 4.5,
        reviews: 97,
        inStock: false,
        discount: 25,
        featured: true,
        tags: ["audio", "wireless"],
        specifications: {
            type: "Over-ear",
            batteryLife: "30 hours",
            connectivity: "Bluetooth 5.0",
            noiseCancelling: true,
        },
    },
    {
        id: "g04",
        name: "Smart Watch Series 5",
        price: 12000,
        originalPrice: 15000,
        image: "https://images.unsplash.com/photo-1544117519-31a4b719223d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        description: "Advanced fitness tracking smartwatch",
        category: "Electronics",
        subcategory: "Wearables",
        rating: 4.2,
        reviews: 156,
        inStock: true,
        discount: 20,
        featured: true,
        tags: ["fitness", "smart"],
        specifications: {
            display: "OLED",
            batteryLife: "18 hours",
            waterResistant: true,
            heartRateMonitor: true,
        },
    },
    {
        id: "g05",
        name: "Gaming Mechanical Keyboard",
        price: 3500,
        originalPrice: null,
        image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        description: "RGB backlit mechanical gaming keyboard",
        category: "Electronics",
        subcategory: "Accessories",
        rating: 4.6,
        reviews: 78,
        inStock: true,
        discount: 0,
        featured: false,
        tags: ["gaming", "rgb"],
        specifications: {
            switchType: "Cherry MX Blue",
            keys: "104",
            backlight: "RGB",
            programmable: true,
        },
    },
    {
        id: "g06",
        name: "Coffee Maker Deluxe",
        price: 8500,
        originalPrice: 10000,
        image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        description: "Premium coffee maker with multiple brewing options",
        category: "Home Appliances",
        subcategory: "Kitchen",
        rating: 4.4,
        reviews: 63,
        inStock: true,
        discount: 15,
        featured: false,
        tags: ["kitchen", "coffee"],
        specifications: {
            capacity: "12 cups",
            type: "Programmable",
            features: ["Auto shut-off", "Brew pause", "Timer"],
            warranty: "2 years",
        },
    },
    {
        id: "g07",
        name: "Yoga Mat Premium",
        price: 1200,
        originalPrice: null,
        image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        description: "Non-slip eco-friendly yoga mat",
        category: "Sports & Fitness",
        subcategory: "Yoga",
        rating: 4.8,
        reviews: 112,
        inStock: false,
        discount: 0,
        featured: true,
        tags: ["fitness", "eco-friendly"],
        specifications: {
            material: "Natural rubber",
            thickness: "6mm",
            size: "183cm x 61cm",
            weight: "1.2kg",
        },
    },
    {
        id: "g08",
        name: "Desk Lamp LED",
        price: 1800,
        originalPrice: 2500,
        image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        description: "Adjustable LED desk lamp with touch controls",
        category: "Home Decor",
        subcategory: "Lighting",
        rating: 4.1,
        reviews: 45,
        inStock: true,
        discount: 28,
        featured: false,
        tags: ["lighting", "led"],
        specifications: {
            brightness: "Adjustable",
            colorTemp: "3000K-6000K",
            powerSource: "USB",
            controlType: "Touch",
        },
    },
    {
        id: "g09",
        name: "Bluetooth Speaker",
        price: 3200,
        originalPrice: 4000,
        image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        description: "Portable waterproof Bluetooth speaker",
        category: "Electronics",
        subcategory: "Audio",
        rating: 4.3,
        reviews: 87,
        inStock: true,
        discount: 20,
        featured: true,
        tags: ["portable", "waterproof"],
        specifications: {
            batteryLife: "12 hours",
            connectivity: "Bluetooth 5.0",
            drivers: "40mm",
            waterproof: true,
        },
    },
    {
        id: "g10",
        name: "Running Shoes",
        price: 4500,
        originalPrice: 5500,
        image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        description: "Lightweight running shoes with extra cushioning",
        category: "Sports & Fitness",
        subcategory: "Footwear",
        rating: 4.6,
        reviews: 134,
        inStock: false,
        discount: 18,
        featured: false,
        tags: ["running", "comfort"],
        specifications: {
            sizeRange: "7-12",
            material: "Mesh upper",
            technology: "Air cushion",
            weight: "280g",
        },
    },
    {
        id: "g11",
        name: "Backpack Travel",
        price: 2800,
        originalPrice: null,
        image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        description: "Durable travel backpack with multiple compartments",
        category: "Travel & Luggage",
        subcategory: "Bags",
        rating: 4.4,
        reviews: 76,
        inStock: true,
        discount: 0,
        featured: false,
        tags: ["travel", "durable"],
        specifications: {
            capacity: "30L",
            material: "Nylon",
            compartments: "Multiple",
            laptopCompartment: true,
        },
    },
    {
        id: "g12",
        name: "Skincare Set",
        price: 2200,
        originalPrice: 3000,
        image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        description: "Complete skincare routine set for all skin types",
        category: "Beauty & Personal Care",
        subcategory: "Skincare",
        rating: 4.7,
        reviews: 203,
        inStock: true,
        discount: 27,
        featured: true,
        tags: ["skincare", "natural"],
        specifications: {
            contents: ["Cleanser", "Toner", "Moisturizer", "Serum"],
            skinType: "All",
            size: "30ml each",
            crueltyFree: true,
        },
    },
];

// // Filter functions for React learning
// const getFeaturedProducts = () => allData.filter((product) => product.featured);
// const getInStockProducts = () => allData.filter((product) => product.inStock);
// const getDiscountedProducts = () =>
//     allData.filter((product) => product.discount > 0);
// const getProductsByCategory = (category) =>
//     allData.filter((product) => product.category === category);
// const getProductsByPriceRange = (min, max) =>
//     allData.filter((product) => product.price >= min && product.price <= max);

// // Export data and filter functions
// export {
//     allData,
//     getFeaturedProducts,
//     getInStockProducts,
//     getDiscountedProducts,
//     getProductsByCategory,
//     getProductsByPriceRange,
// };
